# Defination file - v1.0
name: Test-release 
on:
  workflow_dispatch:  # Allows manual deployment
    inputs:
       run_id:
        description: "Enter Build Run ID or 'latest'"
        required: true
        default: 'latest'
       environment:
        description: "Enter environment"
        required: true
        default: 'dev'

run-name: "Test-release for build # ${{ github.event.inputs.run_id  || 'latest' }}" 
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Print GitHub context
        run: |
          echo "${{ toJson(github) }}"

      - name: Print specific GitHub context values
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"


      - name: Fetch Latest Run ID
        shell: pwsh
        run: |
          # $RUN_ID = "${{ github.event.inputs.run_id || 'latest' }}"
          $RUN_ID = "${{ github.event.inputs.run_id }}"
              if ($RUN_ID -eq "latest") {
                $RUN_ID = ""
              }
          echo "RUN_ID=$RUN_ID" | Out-File -FilePath $env:GITHUB_ENV -Append

          $Environment = "${{ github.event.inputs.environment || 'dev' }}"
          echo "Environment=$Environment" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Debug Environment Variables
        shell: pwsh
        run: |
          echo "RUN_ID=${{ env.RUN_ID }}"
          echo "Environment=${{ env.Environment }}"
  